// <auto-generated />
namespace FGABusinessComponent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class FamilyKey2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FamilyKey2));
        
        string IMigrationMetadata.Id
        {
            get { return "201404171002186_FamilyKey2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
